FROM python:3.12-slim
WORKDIR /app
COPY requirements-api.txt ./requirements-api.txt
RUN pip install --no-cache-dir -r requirements-api.txt
COPY PokePY ./PokePY
COPY migrations ./migrations
COPY alembic.ini ./alembic.ini
EXPOSE 8000
CMD ["python", "-m", "PokePY.api.main"]
